# Generated by Django 4.0.6 on 2022-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0002_server_server_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='description',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_is_active',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu',
            field=models.CharField(default='default', max_length=255, verbose_name='cpu'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk',
            field=models.CharField(default='default', max_length=255, verbose_name='disk'),
        ),
        migrations.AddField(
            model_name='server',
            name='host_information',
            field=models.CharField(default='default', max_length=255, verbose_name='host_information'),
        ),
        migrations.AddField(
            model_name='server',
            name='load_average',
            field=models.CharField(default='default', max_length=255, verbose_name='load_average'),
        ),
        migrations.AddField(
            model_name='server',
            name='memory',
            field=models.CharField(default='default', max_length=255, verbose_name='memory'),
        ),
        migrations.AddField(
            model_name='server',
            name='network',
            field=models.CharField(default='default', max_length=255, verbose_name='network'),
        ),
    ]
