# Generated by Django 4.0.6 on 2022-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0003_remove_server_description_remove_server_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='server',
            name='host_information',
        ),
        migrations.RemoveField(
            model_name='server',
            name='load_average',
        ),
        migrations.RemoveField(
            model_name='server',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='server',
            name='network',
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(default='no_description', max_length=255, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='name', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
