# Generated by Django 4.0.6 on 2022-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0005_alter_server_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='data_active',
            field=models.CharField(default='data_active', max_length=2000, verbose_name='data_active'),
        ),
    ]
